//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetHelper.Domain.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PetHelper.Domain.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Your Email.
        /// </summary>
        public static string ConfirmYourEmail {
            get {
                return ResourceManager.GetString("ConfirmYourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email confirmation is needed.
        /// </summary>
        public static string EmailConfirmationIsNeeded {
            get {
                return ResourceManager.GetString("EmailConfirmationIsNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi! Your email was used for registration in PetHelper! Follow this link to confirm your email address and finish registration {0}.
        /// </summary>
        public static string EmailMessageTemplate {
            get {
                return ResourceManager.GetString("EmailMessageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data found.
        /// </summary>
        public static string InvalidDataFound {
            get {
                return ResourceManager.GetString("InvalidDataFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data found, can&apos;t authenticate user.
        /// </summary>
        public static string InvalidDataFoundCantAuthenticateUser {
            get {
                return ResourceManager.GetString("InvalidDataFoundCantAuthenticateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data found, can&apos;t register user.
        /// </summary>
        public static string InvalidDataFoundCantRegisterUser {
            get {
                return ResourceManager.GetString("InvalidDataFoundCantRegisterUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email address format specified.
        /// </summary>
        public static string InvalidEmailAddressFormatSpecified {
            get {
                return ResourceManager.GetString("InvalidEmailAddressFormatSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No users for specified key were found.
        /// </summary>
        public static string NoUsersForSpecifiedKeyWereFound {
            get {
                return ResourceManager.GetString("NoUsersForSpecifiedKeyWereFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item doesn&apos;t exist.
        /// </summary>
        public static string TheItemDoesntExist {
            get {
                return ResourceManager.GetString("TheItemDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The login is already registered.
        /// </summary>
        public static string TheLoginIsAlreadyRegistered {
            get {
                return ResourceManager.GetString("TheLoginIsAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email is already confirmed.
        /// </summary>
        public static string TheUsersEmailIsAlreadyConfirmed {
            get {
                return ResourceManager.GetString("TheUsersEmailIsAlreadyConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with the provided login doesn&apos;t exist.
        /// </summary>
        public static string UserWithTheProvidedLoginDoesntExist {
            get {
                return ResourceManager.GetString("UserWithTheProvidedLoginDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong password or login.
        /// </summary>
        public static string WrongPasswordOrLogin {
            get {
                return ResourceManager.GetString("WrongPasswordOrLogin", resourceCulture);
            }
        }
    }
}
